name: Build and Notify Slack

on:
  push:
    branches:
      - main

jobs:
  build_and_notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build and analyze application
        run: ANALYZE=true npm run build

      - name: Get bundle size
        id: bundle_size
        run: |
          size=$(du -sh .next/static/chunks | cut -f1)
          echo "size=$size" >> $GITHUB_OUTPUT

      - name: Save bundle size as artifact
        uses: actions/upload-artifact@v3
        with:
          name: bundle-size
          path: .next/static/chunks

      - name: Check if previous bundle size artifact exists
        id: check_artifact
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo
            const artifacts = await github.rest.actions.listArtifactsForRepo({
              owner,
              repo
            })
            const artifact = artifacts.data.artifacts.find(artifact => artifact.name === 'previous-bundle-size')
            if (artifact) {
              return artifact.id
            } else {
              return ''
            }

      - name: Download previous bundle size artifact
        uses: actions/download-artifact@v3
        if: steps.check_artifact.outputs.result != ''
        continue-on-error: true
        with:
          name: previous-bundle-size
          path: .previous_bundle

      - name: Compare bundle sizes
        id: compare_sizes
        run: |
          if [ -d ".previous_bundle" ]; then
            previous_size_kb=$(du -sk .previous_bundle | cut -f1)
            current_size_kb=$(du -sk .next/static/chunks | cut -f1)
            diff=$((current_size_kb - previous_size_kb))
          else
            current_size_kb=$(du -sk .next/static/chunks | cut -f1)
            diff=0
          fi
          echo "diff=$diff" >> $GITHUB_OUTPUT

      - name: Send notification to Slack
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: repo,message,commit,author,eventName,ref,workflow,job,steps
          custom_payload: |
            {
              "attachments": [
                {
                  "fallback": "Current bundle size: ${{ steps.bundle_size.outputs.size }}",
                  "color": "good",
                  "title": "Current Bundle Size",
                  "text": "Current bundle size: *${{ steps.bundle_size.outputs.size }}*"
                },
                {
                  "fallback": "Difference in size: ${{ steps.compare_sizes.outputs.diff }} kB",
                  "color": "good",
                  "title": "Difference in size",
                  "text": "Difference in size: *${{ steps.compare_sizes.outputs.diff }}* kB"
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Update previous bundle size artifact
        run: |
          rm -rf .previous_bundle
          mv .next/static/chunks .previous_bundle

      - name: Save previous bundle size as artifact
        uses: actions/upload-artifact@v3
        with:
          name: previous-bundle-size
          path: .previous_bundle
